name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create file
      run: &&
           echo "test" > release.txt &&
           echo "more" &&
           echo "even more!!!"
    
    - name: Upload Release Asset
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "release.txt"
        update_latest_release: true
        release_id: ${{ github.event.release.id }}
