name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: Ubuntu
          - os: macos-latest
            platform: MacOS
          - os: windows-latest
            platform: Windows
    runs-on: ${{ matrix.os }}
    steps:
    - name: Create file
      run: |
           echo "test" > release-${{ matrix.platform }}.txt &&
           echo "platform ${{ matrix.platform }}" &&
           echo "os ${{ matrix.os }}"
    
    - name: Upload Release Asset
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "release-${{ matrix.platform }}.txt"
        update_latest_release: true
        release_id: ${{ github.event.release.id }}
